# Copy the contents of this file into:
# - Streamlit Cloud: App -> Settings -> Secrets
# - Local development: create .streamlit/secrets.toml (do NOT commit)

# Use at least one of these providers
OPENWEATHER_API_KEY = "your_openweather_key"
WEATHERAPI_KEY = "your_weatherapi_key"

# Optional: weather cache TTL in seconds (default 600)
WEATHER_CACHE_TTL = 600
