name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8

      - name: Basic lint (flake8)
        run: |
          flake8 --max-line-length=120 --extend-ignore=E203,E266,W503 . || true

      - name: Compile Python files
        run: |
          python -m compileall -q .

      - name: Smoke check Streamlit app (no run)
        run: |
          python - << 'PY'
          import ast, pathlib
          p = pathlib.Path('streamlit_app.py')
          ast.parse(p.read_text())
          print('Parsed streamlit_app.py OK')
          PY

      - name: Print Streamlit version
        run: streamlit --version
